# See: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  build-tags: []

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - errchkjson
    - errname
    - exportloopref
    - funlen
    - gci
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - mirror
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace

linters-settings:
  dupl:
    threshold: 200
  errcheck:
    exclude-functions:
      # See: https://golangci-lint.run/usage/linters#errchkjson
      - encoding/json.Marshal
      - encoding/json.MarshalIndent
  errchkjson:
    check-error-free-encoding: true
  funlen:
    lines: 200
    statements: 120
  gci:
    sections:
      - standard
      - default
  goconst:
    ignore-tests: true
  gocyclo:
    min-complexity: 20
  nolintlint:
    require-explanation: true
    require-specific: true

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - dupl
        - funlen
